name: PersonalJoinMessages
version: '1.3.1'
main: cat6172.personaljoinmessages.PersonalJoinMessages
description: Personalized per-player join messages
author: Cat6172
api-version: '1.21'

softdepend: ["PlaceholderAPI"]

commands:
  joinmessage:
    description: customise a players join message
    usage: /joinmessage [set playername message] or [remove playername] or [get playername] or [list] or [reload]
    permission: joinmessage.admin
  leavemessage:
    description: customise a players leave message
    usage: /leavemessage [set playername message] or [remove playername] or [get playername] or [list] or [reload]
    permission: joinmessage.admin
  setjoinmessage:
    description: customise own join message
    usage: /setjoinmessage [message]
    permission: joinmessage.self
  setleavemessage:
    description: customise own leave message
    usage: /setleavemessage [message]
    permission: joinmessage.self
permissions:
  joinmessage.admin:
    description: allows customising any players join and leave message
    default: op
  joinmessage.self:
    description: allows customizing own messages
    default: false
  joinmessage.placeholders:
    description: allows this user's messages to have their placeholders replaced
    default: false
